#!/usr/bin/env bash

set -x

pushd /cse142L
. env.sh
. gradescope_env.sh
. venv/bin/activate

pushd /autograder/source/

# don't do this because it will break deployed assignments.
#for i in CSE141pp-DJR CSE141pp-LabPython ; do
#    (cd $i;
#     git pull
#     python3.9 -m pip install -e .
#    )
#done

LD_LIBRARY_PATH=/cse142L/cfiddle/src/cfiddle/resources/libcfiddle/build/x86_64-pc-linux-gnu/:$LD_LIBRARY_PATH

(cd lab; git pull --rebase)
pushd /autograder/submission
THE_USER=$(qjson ../submission_metadata.json users 0 email)
(unset CSE142L_KEY; python3.9 `which cse142` --no-http --as-user $THE_USER job run --autograder --force --lab $LAB autograde)
cd /autograder/
python3.9 `which cse142-autograde` --lab-directory /autograder/submission --submission /autograder/submission/autograde --targets /autograder/source/lab/targets.csv --results /autograder/results/results.json
exit 0


